In [5]:
import pandas as pd

In [6]:
customers=pd.read_csv(r"C:\Users\ss\Desktop\E-Commerce Business Intelligence & Customer Analytics\Dataset\olist_customers_dataset.csv")

In [7]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [8]:
customers.shape

(99441, 5)

In [9]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [10]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [11]:
customers.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [12]:
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [13]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [14]:
customers.duplicated().sum()

np.int64(0)

In [15]:
customers["customer_id"].nunique()

99441

In [16]:
customers["customer_unique_id"].nunique()

96096

In [17]:
customers["customer_state"].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [18]:
customers["customer_city"].nunique()

4119

In [19]:
customers["customer_zip_code_prefix"].nunique()

14994

## Data Cleaning

In [20]:
customers["customer_id"].nunique()

99441

In [21]:
len(customers["customer_id"])

99441

In [22]:
text_cols=["customer_id", "customer_unique_id", "customer_city", "customer_state"]

for cols in text_cols:
    customers[cols]=customers[cols].str.strip()

In [23]:
customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [24]:
customers.duplicated().sum()

np.int64(0)

In [25]:
customers["customer_zip_code_prefix"].astype(str).str.len().value_counts().sort_index()

customer_zip_code_prefix
4    23995
5    75446
Name: count, dtype: int64

In [26]:
customers["customer_zip_code_prefix"]=(
    customers["customer_zip_code_prefix"].astype(str).str.zfill(5)
)

In [27]:
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix    object
customer_city               object
customer_state              object
dtype: object

In [28]:
customers["customer_zip_code_prefix"].str.len().value_counts()

customer_zip_code_prefix
5    99441
Name: count, dtype: int64

In [29]:
customers.to_csv("Dataset/customers_clean.csv",index=False)