In [1]:
import pandas as pd

In [2]:
review=pd.read_csv(r"C:\Users\ss\Desktop\E-Commerce Business Intelligence & Customer Analytics\Dataset\olist_order_reviews_dataset.csv")

In [3]:
review.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [4]:
review.shape

(99224, 7)

In [5]:
review.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [6]:
review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [7]:
review.describe().T

                count      mean       std  min  25%  50%  75%  max
review_score  99224.0  4.086421  1.347579  1.0  4.0  5.0  5.0  5.0

In [8]:
review.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [9]:
review.duplicated().sum()

np.int64(0)

In [10]:
review["review_id"].nunique()

98410

In [11]:
review["order_id"].nunique()

98673

In [12]:
review["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [13]:
review["review_id"].value_counts().gt(1).sum()

np.int64(789)

In [14]:
review["order_id"].value_counts().gt(1).sum()

np.int64(547)

In [15]:
review["review_comment_title"]=review["review_comment_title"].fillna("No comment")

In [16]:
review["review_comment_message"]=review["review_comment_message"].fillna("No comment")

In [17]:
# Replacing missing review with no comment because customer can submit rating without review comment

In [18]:
review[["review_comment_title", "review_comment_message"]].isna().sum()

review_comment_title      0
review_comment_message    0
dtype: int64

In [19]:
# converting review date column datatype to date type

In [20]:
review["review_creation_date"]=pd.to_datetime(review["review_creation_date"],errors="coerce")

In [21]:
review["review_answer_timestamp"]=pd.to_datetime(review["review_answer_timestamp"],errors="coerce")

In [22]:
review[["review_answer_timestamp","review_creation_date"]].dtypes

review_answer_timestamp    datetime64[ns]
review_creation_date       datetime64[ns]
dtype: object

In [23]:
review[["review_answer_timestamp","review_creation_date"]].isna().sum()

review_answer_timestamp    0
review_creation_date       0
dtype: int64

In [24]:
# Review table cleaning completed: missing comments were labeled as "No comment"
# and review date columns were converted to datetime format.

In [27]:
review.to_csv("Dataset/review_clean.csv",index=False)

In [31]:
review_clean=pd.read_csv(r"C:\Users\ss\Desktop\E-Commerce Business Intelligence & Customer Analytics\Dataset\review_clean.csv")

In [32]:
review_mysql=review_clean.copy()

In [33]:
review_mysql["review_comment_title"]=review_mysql["review_comment_title"].fillna('').astype(str).str.replace('\n',''
,regex=False).str.replace('\r','',regex=False)

In [34]:
review_mysql["review_comment_message"]=review_mysql["review_comment_message"].fillna('').astype(str).str.replace('\n',''
,regex=False).str.replace('\r','',regex=False)

In [40]:
review_mysql.to_csv(r"Dataset\review_clean_mysql.csv",index=False,encoding='utf-8')

In [41]:
print(review_mysql.shape)

(99224, 7)

In [42]:
import csv

file_path = "Dataset/review_clean_mysql.csv"

with open(file_path, "r", encoding="utf-8", newline="") as f:
    rows = list(csv.reader(f))

print("Rows including header:", len(rows))
print("Data rows:", len(rows) - 1)
print("Columns:", len(rows[0]))

Rows including header: 99225
Data rows: 99224
Columns: 7

In [45]:
import mysql.connector
print("MySQL connector is installed")

MySQL connector is installed

In [44]:
%pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.7 MB 2.5 MB/s eta 0:00:07
   -- ------------------------------------- 1.0/17.7 MB 2.3 MB/s eta 0:00:08
   -- ------------------------------------- 1.3/17.7 MB 1.9 MB/s eta 0:00:09
   ---- ----------------------------------- 1.8/17.7 MB 2.0 MB/s eta 0:00:08
   ----- ---------------------------------- 2.4/17.7 MB 2.1 MB/s eta 0:00:08
   ------ --------------------------------- 2.9/17.7 MB 2.3 MB/s eta 0:00:07
   ------- -------------------------------- 3.4/17.7 MB 2.3 MB/s eta 0:00:07
   -------- ------------------------------- 3.7/17.7 MB 2.1 MB/s eta 0:00:07
   -------- ------------------------------- 3.9/17.7 MB 2.0 MB/s eta 0:00:07
   --------- ------------------------------ 4.2/17.7 MB 1.9 MB/s eta 0:00:07
   ---------- ----------------------------- 4.7/17.7 MB 2.0 MB/s eta 0:00:07
   ---------- ----------------------------- 4.7/17.7 MB 2.0 MB/s eta 0:00:07
   ----------- ---------------------------- 5.2/17.7 MB 1.9 MB/s eta 0:00:07
   ------------ --------------------------- 5.5/17.7 MB 1.9 MB/s eta 0:00:07
   ------------- -------------------------- 5.8/17.7 MB 1.8 MB/s eta 0:00:07
   ------------- -------------------------- 6.0/17.7 MB 1.7 MB/s eta 0:00:07
   -------------- ------------------------- 6.3/17.7 MB 1.7 MB/s eta 0:00:07
   -------------- ------------------------- 6.6/17.7 MB 1.7 MB/s eta 0:00:07
   --------------- ------------------------ 6.8/17.7 MB 1.7 MB/s eta 0:00:07
   ---------------- ----------------------- 7.1/17.7 MB 1.7 MB/s eta 0:00:07
   ----------------- ---------------------- 7.6/17.7 MB 1.7 MB/s eta 0:00:07
   ----------------- ---------------------- 7.9/17.7 MB 1.7 MB/s eta 0:00:06
   ------------------ --------------------- 8.1/17.7 MB 1.7 MB/s eta 0:00:06
   ------------------- -------------------- 8.7/17.7 MB 1.7 MB/s eta 0:00:06
   ------------------- -------------------- 8.7/17.7 MB 1.7 MB/s eta 0:00:06
   -------------------- ------------------- 8.9/17.7 MB 1.6 MB/s eta 0:00:06
   --------------------- ------------------ 9.4/17.7 MB 1.6 MB/s eta 0:00:06
   ---------------------- ----------------- 10.0/17.7 MB 1.7 MB/s eta 0:00:05
   ------------------------ --------------- 10.7/17.7 MB 1.8 MB/s eta 0:00:04
   -------------------------- ------------- 11.5/17.7 MB 1.8 MB/s eta 0:00:04
   --------------------------- ------------ 12.3/17.7 MB 1.9 MB/s eta 0:00:03
   ----------------------------- ---------- 12.8/17.7 MB 1.9 MB/s eta 0:00:03
   ------------------------------ --------- 13.4/17.7 MB 1.9 MB/s eta 0:00:03
   -------------------------------- ------- 14.4/17.7 MB 2.0 MB/s eta 0:00:02
   ---------------------------------- ----- 15.2/17.7 MB 2.1 MB/s eta 0:00:02
   ------------------------------------ --- 16.3/17.7 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 16.8/17.7 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  17.3/17.7 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 2.2 MB/s  0:00:08
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0
Note: you may need to restart the kernel to use updated packages.

In [48]:
df = pd.read_csv("Dataset/review_clean_mysql.csv")

In [46]:
conn=mysql.connector.connect(host='localhost',user='root',password="Anushka#20",database="olist_ecommerce")
print("connect successfully")

connect successfully

In [47]:
cursor = conn.cursor()

In [49]:
query = """
INSERT INTO review_clean
(review_id, order_id, review_score, review_comment_title,
 review_comment_message, review_creation_date, review_answer_timestamp)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""
data = df.where(pd.notnull(df), None).values.tolist()

cursor.executemany(query, data)

conn.commit()

print("Rows inserted:", cursor.rowcount)

cursor.close()
conn.close()

Rows inserted: 99224