In [6]:
import pandas as pd

In [7]:
seller=pd.read_csv(r"C:\Users\ss\Desktop\E-Commerce Business Intelligence & Customer Analytics\Dataset\olist_sellers_dataset.csv")

In [8]:
seller.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [9]:
seller.shape

(3095, 4)

In [10]:
seller.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [11]:
seller.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [12]:
seller.describe().T

,count,mean,std,min,25%,50%,75%,max
seller_zip_code_prefix,3095.0,32291.059451,32713.45383,1001.0,7093.5,14940.0,64552.5,99730.0

In [13]:
seller.isna().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [14]:
seller.duplicated().sum()

np.int64(0)

In [15]:
seller["seller_id"].nunique()

3095

In [16]:
len(seller)

3095

In [17]:
seller["seller_state"].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
PI       1
AC       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

In [18]:
seller_clean=seller.copy()

In [19]:
seller_clean["seller_zip_code_prefix"]=seller_clean["seller_zip_code_prefix"].astype(str).str.zfill(5)

In [20]:
seller_clean["seller_zip_code_prefix"].str.len().value_counts()

seller_zip_code_prefix
5    3095
Name: count, dtype: int64

In [21]:
seller_clean.to_csv("Dataset/seller_clean.csv",index=False)